-- AlterTable
ALTER TABLE `projects` ADD COLUMN `projectType` ENUM('POTENTIAL_CLIENT', 'QUALIFIED_CLIENT', 'CURRENT_CLIENT', 'PAST_CLIENT', 'PERSONAL_PROJECT', 'PROFESSIONAL_PROJECT') NOT NULL DEFAULT 'PERSONAL_PROJECT';

-- AlterTable
ALTER TABLE `timeline_events` MODIFY `eventDate` DATETIME(3) NULL;
